name: K3s Matrix Testing 

on: [push]

jobs:

  get-versions:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - id: get-k3s-versions
      run: |
        releases=$(curl -s https://api.github.com/repos/k3s-io/k3s/releases | jq -r '.[].tag_name' | head -n 5)
        matrix=$(echo $releases | jq -R 'split("\n") | map(select(test("rc") | not))')
        echo "matrix=${matrix}" >> $GITHUB_ENV

    - id: write-matrix
      run: echo ${matrix} > matrix.json

    - uses: actions/upload-artifact@v3
      with:
        name: matrix
        path: matrix.json

  test:

    needs: get-versions
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/download-artifact@v3
      with:
        name: matrix
            
    - id: read-matrix
      run: |
        matrix=$(cat matrix.json)
        echo "matrix=${matrix}" >> $GITHUB_ENV

    - name: Test
      env:
        k8s_version: ${{ matrix.k8s_version }}  
      run: |
        k3s_version="v$k8s_version+k3s1"
        curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=$k3s_version sh -
        kubectl create deploy nginx --image=nginx
        kubectl rollout status deploy nginx
        kubectl delete deploy nginx
