name: K3s Matrix Testing

on: [push]

jobs:

  get-versions:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get K3s Versions
      id: get-k3s-versions
      run: |
        releases=$(curl -s https://api.github.com/repos/k3s-io/k3s/releases | jq -r '.[].tag_name' | head -n 5)
        echo $releases | jq -R 'split("\n") | map(select(test("rc") | not))'
        echo "matrix=$(echo $releases | jq -R 'split("\n") | map(select(test("rc") | not))')" >> $GITHUB_ENV

    - name: Set Matrix
      id: set-matrix  
      run: |
        matrix="${MATRIX//v/}"
        matrix="${matrix//+k3s/}"
        echo "matrix=${matrix}" >> $GITHUB_ENV

  test:

    needs: get-versions
    runs-on: ubuntu-latest

    strategy:
      matrix: ${{fromJson(needs.get-versions.outputs.matrix)}}

    steps:
    - uses: actions/checkout@v2
      
    - name: Test
      env: 
        k8s_version: ${{ matrix.k8s_version }}  
      run: |
        k3s_version="v$k8s_version+k3s1"
        curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=$k3s_version sh -
        kubectl create deploy nginx --image=nginx
        kubectl rollout status deploy nginx
        kubectl delete deploy nginx
